DROP DATABASE IF EXISTS `mydb`;
CREATE DATABASE `mydb`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 'mysql';
GRANT ALL PRIVILEGES ON mydb.* TO 'rashmi'@'localhost' IDENTIFIED BY 'rashmi99'

WITH GRANT OPTION;
FLUSH PRIVILEGES;